// Generated by CoffeeScript 1.3.3
(function() {
  var colors, getBookmarkData, renderLinks, saveBookmarkData, syncdata;

  syncdata = null;

  colors = ['silver', 'black', 'purple', 'blue', 'green', 'yellow', 'orange', 'red', 'pink'];

  getBookmarkData = function(bookmark) {
    var default_data, hash;
    hash = bookmark.title;
    return default_data = {
      'id': bookmark.id,
      'link': bookmark.url
    };
  };

  saveBookmarkData = function(key, data) {
    var content;
    content = JSON.stringify(data);
    return $.ajax({
      url: 'https://api.github.com/gists',
      type: 'POST',
      dataType: 'json',
      data: JSON.stringify({
        'description': 'tek newtab sync data',
        'public': false,
        'files': {
          'sync.json': {
            'content': content
          }
        }
      }),
      success: function(data, textStatus, jqXHR) {
        console.log("gisted", data);
        chrome.bookmarks.update(key, {
          title: data.id
        });
        return localStorage[data.id] = content;
      }
    });
  };

  renderLinks = function(data) {
    var html, template;
    template = Handlebars.compile($("#links-template").html());
    html = template({
      rows: data
    });
    $('#links').html(html);
    $("a[data-pinned='true']").click(function(e) {
      if (e.which === 1 && !e.metaKey && !e.shiftKey) {
        chrome.tabs.getCurrent(function(tab) {
          return chrome.tabs.update(tab.id, {
            'pinned': true
          });
        });
        return;
      }
      chrome.tabs.create({
        'pinned': true,
        'selected': false,
        'url': $(this).attr("href")
      });
      return false;
    });
    return $('.link-image').bind('drop', function(ev) {
      var dt, file, key, reader, target_img;
      dt = ev.originalEvent.dataTransfer;
      console.log(dt.types, dt.files[0]);
      key = ev.target.dataset.key;
      target_img = $(ev.target);
      target_img.removeClass('dragover');
      if (dt.types[0] !== "Files") {
        return true;
      }
      if (dt.files.length !== 1) {
        ev.stopPropagation();
        return false;
      }
      file = dt.files[0];
      if (file.type.indexOf("image") === 0) {
        reader = new FileReader();
        reader.onload = function(e) {
          var imgsrc;
          imgsrc = e.target.result;
          target_img.css("background", "url(" + imgsrc + ")");
          return chrome.bookmarks.get(key, function(bookmark) {
            var bookmark_data;
            bookmark_data = getBookmarkData(bookmark[0]);
            bookmark_data['rawimg'] = imgsrc;
            return saveBookmarkData(key, bookmark_data);
          });
        };
        reader.readAsDataURL(file);
      }
      ev.stopPropagation();
      return false;
    }).bind('dragenter', function(ev) {
      $(ev.target).addClass('dragover');
      return false;
    }).bind('dragleave', function(ev) {
      $(ev.target).removeClass('dragover');
      return false;
    }).bind('dragover', function(ev) {
      return false;
    });
  };

  $('#settings-toggle').click(function() {
    $('.settings').toggle();
    return false;
  });

  chrome.storage.sync.get(null, function(data) {
    var newdata;
    syncdata = data;
    newdata = [];
    return chrome.bookmarks.getTree(function(tree) {
      var mytree;
      mytree = null;
      $.each(tree[0].children[1].children, function(i, subtree) {
        if (subtree.title === 'newtab') {
          return mytree = subtree;
        }
      });
      return $.each(mytree.children, function(i, subtree) {
        var row;
        row = $('<ul>');
        $('body').append(row);
        return $.each(subtree.children, function(i, bookmark) {
          var color, color_select, img_div, img_url, li, link, opt, pin_check, pin_label, setting_div, _i, _len;
          li = $('<li>');
          row.append(li);
          link = $('<a>').attr('class', syncdata["color-" + bookmark.url]).attr('href', bookmark.url).data('pinned', syncdata["pinned-" + bookmark.url]);
          li.append(link);
          link.click(function(e) {
            if (link.data('pinned')) {
              if (e.which === 1 && !e.metaKey && !e.shiftKey) {
                chrome.tabs.getCurrent(function(tab) {
                  return chrome.tabs.update(tab.id, {
                    'pinned': true
                  });
                });
                return;
              }
              chrome.tabs.create({
                'pinned': true,
                'selected': false,
                'url': $(this).attr("href")
              });
              return false;
            }
          });
          img_div = $('<div>').attr('class', "link-image").css('background', "url(" + syncdata["image-" + bookmark.url] + ")");
          link.append(img_div);
          setting_div = $('<div>').attr('class', 'settings');
          li.append(setting_div);
          color_select = $('<select>');
          setting_div.append(color_select);
          for (_i = 0, _len = colors.length; _i < _len; _i++) {
            color = colors[_i];
            opt = $('<option>').text(color);
            color_select.append(opt);
          }
          color_select.change(function() {
            var key, val;
            val = $(this).val();
            key = "color-" + bookmark.url;
            data = {};
            data[key] = val;
            link.attr('class', val);
            return chrome.storage.sync.set(data);
          });
          img_url = $('<input>').attr('class', 'img-url').val(syncdata["image-" + bookmark.url]).change(function() {
            var key;
            key = "image-" + bookmark.url;
            data = {};
            data[key] = $(this).val();
            chrome.storage.sync.set(data);
            return img_div.css('background', "url(" + data[key] + ")");
          });
          setting_div.append(img_url);
          pin_label = $('<label>').text('Pinned');
          setting_div.append(pin_label);
          pin_check = $('<input>').attr('type', 'checkbox').attr('checked', syncdata["pinned-" + bookmark.url]).change(function() {
            var key;
            key = "pinned-" + bookmark.url;
            data = {};
            data[key] = $(this).attr('checked') === 'checked';
            chrome.storage.sync.set(data);
            return link.data('pinned', data[key]);
          });
          return pin_label.append(pin_check);
        });
      });
    });
  });

}).call(this);
